--- #YAML:1.0
name:               AI-NeuralNet-Hopfield
version:            0.08
abstract:           A simple Hopfiled Network Implementation.
author:
    - leprevost <leprevost@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::More:  0
requires:
    Math::SparseMatrix:  0.03
    Moose:               2.0604
    perl:                5.1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
